### ISSUE TITLE
Lovelace card

### ISSUE THREAD

**Issue by SteveRMann** [gagebenne/home-assistant-dexcom#1]
I am new to Lovelace- do you have the **ui-lovelace.yaml** lines for the card in your Readme?

**Comment by gagebenne** [comment]
Yep, no worries:
```yaml
cards:
  - entities:
      - entity: sensor.dexcom_glucose_value
      - entity: sensor.dexcom_glucose_trend
    type: glance
    show_name: true
  - type: sensor
    entity: sensor.dexcom_glucose_value
    graph: line
    hours_to_show: 3
    name: Glucose value history
type: vertical-stack
```
Their UI makes these kind of vertical stacks pretty easy via the visual editor.
